name: Java CI Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test -e
    - name: List contents of the target directory
      run: ls -lR target/

    - name: Upload Surefire Reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: target/surefire-reports
    - name: List files in test resources
      run: ls -l